'use client';
import * as React from 'react';
import { Badge } from '@/ui/primitives/Badge';
import { Button } from '@/ui/primitives/Button';
import type { ResultArtifact } from '@/domain/types';

export type EvidenceState = 'available' | 'stale' | 'partial' | 'unavailable';
export type CiteFn = (ref: string, claim: string, state: EvidenceState) => React.ReactNode;
export interface ResultBlockProps { a: ResultArtifact; cite: CiteFn; onPrepare: (query: string) => void }

/** Result blocks RB-01…RB-12 (SA §07). Declared at module scope on purpose: defining this inside the
 *  session component would make React see a new component type on every render and remount the whole
 *  result subtree, which drops scroll position and breaks the citation focus return required by P-04. */
export function ResultBlock({ a, cite, onPrepare }: ResultBlockProps) {
    const p: any = a.payload;
    switch (a.type) {
      case 'RB-12': return <section id={a.anchor} style={{ padding: 16, border: '1px solid var(--am-warning-border)', borderRadius: 8, background: 'var(--am-warning-surface)', maxWidth: 760, display: 'flex', flexDirection: 'column', gap: 8 }}><h2 style={{ margin: 0, font: '700 14px/20px var(--am-font-ui)', color: 'var(--am-warning-text)' }}>{a.title}</h2><p style={{ margin: 0, font: '400 14px/22px var(--am-font-ui)' }}><b>Source [{p.source}]</b> {p.reason}. Affected: {p.affected.join('; ')}. Unaffected: {p.unaffected.join('; ')}.</p><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><Button size="sm">Retry source [{p.source}] · review cost</Button><Button size="sm">Prepare depth-1 scope</Button></div></section>;
      case 'RB-01': return <section id={a.anchor} style={{ maxWidth: 760, display: 'flex', flexDirection: 'column', gap: 16 }}><h2 style={{ margin: 0, font: '700 22px/30px var(--am-font-ui)' }}>Answer</h2><p style={{ margin: 0 }}>{p.text} {a.claims.map(c => <React.Fragment key={c.claimId}>{c.citations.map(ci => <React.Fragment key={ci.sourceRef}>{cite(ci.sourceRef, c.text, ci.state)} </React.Fragment>)}</React.Fragment>)}</p><div role="note" style={{ display: 'flex', gap: 12, padding: '12px 16px', border: '1px solid var(--am-warning-border)', borderRadius: 8, background: 'var(--am-warning-surface)', color: 'var(--am-warning-text)', font: '400 14px/22px var(--am-font-ui)' }}><b>Material caveat.</b> {p.caveat}</div></section>;
      case 'RB-02': return <section id={a.anchor} style={{ maxWidth: 760 }}><h3 style={{ margin: '0 0 8px', font: '700 18px/26px var(--am-font-ui)' }}>{a.title}</h3><p style={{ margin: 0 }}>{p.text} {a.claims.flatMap(c => c.citations.map(ci => <React.Fragment key={ci.sourceRef}>{cite(ci.sourceRef, c.text, ci.state)} </React.Fragment>))}</p></section>;
      case 'RB-06': { const max = Math.max(...p.points.map((x: any) => x.y ?? 0), 1); return <figure id={a.anchor} style={{ margin: 0, maxWidth: 760, minWidth: 0 }}><figcaption style={{ font: '700 18px/26px var(--am-font-ui)', marginBottom: 12 }}>{a.title} <span style={{ font: '400 12px/18px var(--am-font-ui)', color: 'var(--am-text-tertiary)' }}>· {p.unit} · X — {p.xLabel} · source [1]</span></figcaption><div tabIndex={0} role="group" aria-label={a.title + ' — scrollable plot'} style={{ overflowX: 'auto', maxWidth: '100%', border: '1px solid var(--am-border-subtle)', background: 'var(--am-chart-canvas)' }}><div role="img" aria-label={a.title + ': ' + p.points.map((x: any) => x.x + ' ' + (x.y ?? 'no data')).join(', ')} style={{ padding: 16, display: 'flex', alignItems: 'flex-end', gap: 8, height: 240, boxSizing: 'border-box', minWidth: 420 }}>{p.points.map((x: any) => <div key={x.x} style={{ flex: '1 0 48px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, justifyContent: 'flex-end', height: '100%' }}><span className="am-num" style={{ font: '400 11px/16px var(--am-font-ui)', fontVariantNumeric: 'tabular-nums lining-nums', color: 'var(--am-text-secondary)' }}>{x.y == null ? '—' : x.y.toLocaleString('en-US')}</span><div style={{ width: 40, height: x.y == null ? 0 : Math.round((x.y / max) * 160), background: 'var(--am-chart-s1)' }} /><span style={{ font: '400 12px/18px var(--am-font-ui)', color: 'var(--am-chart-label)' }}>{x.x}</span></div>)}</div></div><details style={{ marginTop: 8 }}><summary style={{ color: 'var(--am-text-link)', cursor: 'pointer' }}>Equivalent table</summary><table className="am-num" style={{ borderCollapse: 'collapse', font: '400 14px/24px var(--am-font-ui)', fontVariantNumeric: 'tabular-nums lining-nums' }}><thead><tr><th style={{ textAlign: 'left', padding: '8px 12px' }}>Day (UTC)</th><th style={{ textAlign: 'right', padding: '8px 12px' }}>{p.unit}</th></tr></thead><tbody>{p.points.map((x: any) => <tr key={x.x}><td style={{ padding: '8px 12px' }}>{x.x}</td><td style={{ padding: '8px 12px', textAlign: 'right' }}>{x.y == null ? '—' : x.y.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td></tr>)}</tbody></table></details></figure>; }
      case 'RB-05': return <section id={a.anchor} style={{ minWidth: 0, maxWidth: '100%' }}><h3 style={{ margin: '0 0 12px', font: '700 18px/26px var(--am-font-ui)' }}>{a.title}</h3><div tabIndex={0} role="group" aria-label={a.title + ' — scrollable table'} style={{ border: '1px solid var(--am-border-subtle)', background: 'var(--am-bg-surface)', overflowX: 'auto', maxWidth: '100%' }}><table className="am-num am-table" style={{ width: '100%', minWidth: 900, borderCollapse: 'collapse', font: '400 14px/24px var(--am-font-ui)', fontVariantNumeric: 'tabular-nums lining-nums' }}><caption className="am-sr">{a.title}</caption><thead><tr style={{ color: 'var(--am-text-secondary)', textAlign: 'left' }}>{p.columns.map((c: string, i: number) => <th key={c} scope="col" style={{ padding: 'var(--am-cell-pad)', borderBottom: '1px solid var(--am-border-subtle)', textAlign: i === 2 || i === 3 ? 'right' : 'left' }}>{c}</th>)}</tr></thead><tbody>{p.rows.map((r: any) => <tr key={r.from} className="am-row" style={{ height: 'var(--am-row-h)', borderBottom: '1px solid var(--am-border-subtle)', background: r.unavailable ? 'var(--am-warning-surface)' : undefined }}><td className="am-mono" style={{ padding: 0 }}><a href={'/wallet/solana/' + r.full} style={{ display: 'flex', alignItems: 'center', minHeight: 'var(--am-row-h)', padding: 'var(--am-cell-pad)', color: 'inherit', textDecoration: 'none' }}>{r.from}</a></td><td style={{ padding: 'var(--am-cell-pad)', color: 'var(--am-text-tertiary)', font: '400 12px/18px var(--am-font-ui)' }}>{r.label || '—'}</td><td style={{ padding: 'var(--am-cell-pad)', textAlign: 'right', color: r.unavailable ? 'var(--am-warning-text)' : undefined }}>{r.amount ?? '— unavailable'}</td><td style={{ padding: 'var(--am-cell-pad)', textAlign: 'right' }}>{r.n}</td><td style={{ padding: 'var(--am-cell-pad)' }}>{r.first}</td><td style={{ padding: 'var(--am-cell-pad)' }}>{r.last}</td><td style={{ padding: 'var(--am-cell-pad)' }}>{cite(String(r.ref), 'row ' + r.from, r.unavailable ? 'unavailable' : 'available')}</td></tr>)}</tbody></table></div></section>;
      case 'RB-07': return <section id={a.anchor} style={{ maxWidth: 760, borderTop: '1px solid var(--am-border-subtle)', paddingTop: 24 }}><h3 style={{ margin: '0 0 8px', font: '700 18px/26px var(--am-font-ui)' }}>{a.title}</h3>{p.sources.map((s: any) => <div key={s.n} style={{ display: 'flex', gap: 12, padding: '8px 0', borderTop: '1px solid var(--am-border-subtle)', font: '400 14px/22px var(--am-font-ui)' }}><span style={{ color: 'var(--am-text-link)', fontWeight: 700 }}>[{s.n}]</span><div style={{ flex: 1 }}>{s.name}<div style={{ font: '400 12px/18px var(--am-font-ui)', color: 'var(--am-text-tertiary)' }}>{s.time} · Coverage: {s.coverage}</div></div><Badge tone={s.state === 'available' ? 'success' : s.state === 'stale' ? 'warning' : 'info'}>{s.fresh}</Badge></div>)}</section>;
      case 'RB-11': return <section id={a.anchor} style={{ maxWidth: 760 }}><h3 style={{ margin: '0 0 8px', font: '700 18px/26px var(--am-font-ui)' }}>{a.title}</h3>{p.items.map((f: any) => <div key={f.t} style={{ display: 'flex', alignItems: 'center', gap: 16, minHeight: 44, padding: '8px 16px', border: '1px solid var(--am-border-subtle)', borderRadius: 8, background: 'var(--am-bg-surface)', marginBottom: 8 }}><div style={{ flex: 1 }}><div>{f.t}</div><div style={{ font: '400 12px/18px var(--am-font-ui)', color: 'var(--am-text-tertiary)' }}>{f.s}</div></div><Button size="sm" onClick={() => onPrepare(f.t)}>Prepare</Button></div>)}</section>;
      case 'RB-09': return <section id={a.anchor} style={{ minWidth: 0, maxWidth: '100%' }}><h3 style={{ margin: '0 0 8px', font: '700 18px/26px var(--am-font-ui)' }}>{a.title}</h3><div tabIndex={0} role="group" aria-label={a.title + ' — scrollable edge table'} style={{ overflowX: 'auto', maxWidth: '100%' }}><table className="am-num" style={{ borderCollapse: 'collapse', font: '400 14px/24px var(--am-font-ui)', fontVariantNumeric: 'tabular-nums lining-nums', background: 'var(--am-bg-surface)', border: '1px solid var(--am-border-subtle)' }}><caption className="am-sr">Equivalent edge table</caption><thead><tr style={{ textAlign: 'left', color: 'var(--am-text-secondary)' }}><th style={{ padding: '8px 12px' }}>From</th><th style={{ padding: '8px 12px' }}>To</th><th style={{ padding: '8px 12px', textAlign: 'right' }}>Amount (USDC)</th><th style={{ padding: '8px 12px' }}>Depth · evidence</th></tr></thead><tbody>{p.edges.map((e: any) => <tr key={e.from + e.to} style={{ borderTop: '1px solid var(--am-border-subtle)' }}><td className="am-mono" style={{ padding: '8px 12px' }}>{e.from}</td><td className="am-mono" style={{ padding: '8px 12px' }}>{e.to}</td><td style={{ padding: '8px 12px', textAlign: 'right' }}>{e.amount}</td><td style={{ padding: '8px 12px', color: 'var(--am-warning-text)' }}>2 · [2] stale</td></tr>)}</tbody></table></div><p style={{ font: '400 12px/18px var(--am-font-ui)', color: 'var(--am-text-tertiary)' }}>{p.note}</p></section>;
      default: return null;
    }
  }
